### ISSUE TITLE
buildDocs broken for Java13

### ISSUE THREAD

**Issue by umeshdangat** [Yelp/platypus#16]
buildDocs is broken post Java13 upgrade. Stacktrace [here](https://gist.github.com/umeshdangat/4ca22a91b3cb8a97711143019caba695). Probably the dependency plugin `pseudomuto/protoc-gen-doc` does not work with Java13. 

Workaround: buildDocs still works with Java12. Until this is fixed, ./gradlew buildDocs will work if your JAVA_HOME is set to java12.  The output of buildDocs is an `index.html` file which can be rendered in the browser.

**Comment by sarthakn7** [comment]
The `pseudomuto/protoc-gen-doc` plugin currently does not support JDK 13, as `docker-java` does not support it. We need to update `pseudomuto/protoc-gen-doc` dependency once a new version with JDK 13 support comes out.

Ref: https://github.com/bmuschko/gradle-docker-plugin/issues/885

**Comment by sarthakn7** [comment]
Not doing this since we have replaced the protoc-gen-doc generated docs with swagger docs.
